"""init

Revision ID: 1
Revises: 
Create Date: 2025-07-22 21:47:07.773668

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'crypto_currency_rate',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('from_currency', sa.String(), nullable=False),
        sa.Column('to_currency', sa.String(), nullable=False),
        sa.Column('price', sa.Numeric(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index('idx_crypto_currency_rate_created_at', 'crypto_currency_rate', ['created_at'])

    op.create_table(
        'crypto_currency_task',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('from_currency', sa.String(), nullable=False),
        sa.Column('to_currency', sa.String(), nullable=False),
        sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.execute(
        """
        INSERT INTO crypto_currency_task (from_currency, to_currency, next_attempt_at, created_at, updated_at)
        VALUES 
        ('BTC', 'USDT', now(), now(), now()),
        ('ETH', 'USDT', now(), now(), now()),
        ('USDT', 'BTC', now(), now(), now()),
        ('USDT', 'ETH', now(), now(), now()),
        ('ETH', 'BTC', now(), now(), now()),
        ('BTC', 'ETH', now(), now(), now());
        """,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_crypto_currency_rate_created_at', table_name='crypto_currency_rate')
    op.drop_table('crypto_currency_task')
    op.drop_table('crypto_currency_rate')
    # ### end Alembic commands ###
