REQUEST_CRYPTO_CURRENCY_DELAY = 30  # seconds
CRYPTO_CURRENCY_RATE_LIFETIME = 7 * 24 * 60 * 60  # 7 days
CRYPTO_CURRENCY_RATE_ACTUAL_LIFETIME = 60  # seconds
CRYPTO_CURRENCY_RATE_TASK_PERIOD = 1  # seconds
CRYPTO_CURRENCY_RATE_TIMESTAMP_TOLERANCE = 30  # seconds
